# Generated by Django 4.1 on 2022-08-11 11:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0003_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['product_name'], unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('offer_price', models.IntegerField(blank=True, null=True)),
                ('image1', models.ImageField(upload_to='photos/Products')),
                ('image2', models.ImageField(upload_to='photos/Products')),
                ('image3', models.ImageField(upload_to='photos/Products')),
                ('image4', models.ImageField(upload_to='photos/Products')),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product_offer', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
            ],
        ),
    ]
