# Generated by Django 4.1 on 2022-08-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'products', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='products',
            name='is_offer_active',
            field=models.BooleanField(default=True),
        ),
    ]
