# Generated by Django 4.1 on 2022-09-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_products_options_products_is_offer_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='is_offer_active',
        ),
        migrations.RemoveField(
            model_name='products',
            name='offer_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_offer',
        ),
    ]
