# Generated by Django 4.1 on 2022-09-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_offercategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=200, unique=True)),
                ('image1', models.ImageField(upload_to='photos/Banners')),
                ('image2', models.ImageField(upload_to='photos/Banners')),
                ('image3', models.ImageField(upload_to='photos/Banners')),
            ],
        ),
    ]
