# Generated by Django 4.1 on 2022-08-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('accounts', '0003_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Addresss',
        ),
    ]
