# Generated by Django 4.1 on 2022-08-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_addresss_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresss',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='addresss',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
