# Generated by Django 4.1 on 2022-08-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_creater_at_payment_created_at_and_more'),
        ('accounts', '0006_rename_firstname_addresss_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addresss',
        ),
    ]
