# Generated by Django 4.1 on 2022-09-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phonenumbe',
            new_name='phonenumber',
        ),
    ]
