# Generated by Django 4.1 on 2022-08-17 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
