# Generated by Django 4.1 on 2022-09-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_coupon_usedcoupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
