# Generated by Django 4.1 on 2022-08-31 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_created_at_order_is_ordered_order_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zip_code',
            new_name='pincode',
        ),
    ]
