# Generated by Django 4.1 on 2022-09-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_address_alter_orderproduct_order_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Confirmed', 'Confirmed'), ('Accepted', 'Accepted'), ('Out For Delivery', 'Out For Delivery'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=30, null=True),
        ),
    ]
