# Generated by Django 4.1 on 2022-09-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Confirmed', 'Confirmed'), ('Accepted', 'Accepted'), ('Out For Delivery', 'Out For Delivery'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Confirmed', max_length=30, null=True),
        ),
    ]
